name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Aparência
          template: terminal
          extras_css: |
            :root {
              --color-bg-default: #0b2e13;
              --color-text-primary: #e8f5e9;
            }
          config_timezone: America/Sao_Paulo

          # Métricas principais
          base: header, activity, community, repositories

          # Linguagens
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Contribuições
          plugin_isocalendar: yes

          # Hábitos
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
